# Generated by Django 3.0.1 on 2020-05-30 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyForm', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='name',
            field=models.CharField(help_text='Username Must Contain Alphabet', max_length=30, verbose_name='Username'),
        ),
    ]
