# Generated by Django 3.0.1 on 2020-05-30 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyForm', '0002_auto_20200530_1203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='name',
            field=models.CharField(max_length=30, verbose_name='Username'),
        ),
    ]
